export enum ApiRequestType {
  Configuration = 'configuration',
  MoviePopular = 'movie/popular',
  MovieTopRated = 'movie/top_rated',
  MovieUpcoming = 'movie/upcoming',
  TvPopular = 'tv/popular',
  TvTopRated = 'tv/top_rated',
  Search = 'search/multi?query=',
  Credits = '/credits',
  Person = 'person/',
  PersonCast = '/combined_credits',
  SearchPerson = 'search/person?query=',
  Rating = 'rating?guest_session_id=',
  GuestSession = 'authentication/guest_session/new',
  PersonList = 'person/popular?page=',
}
